const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/27.jpg',
      price: 120,
      brand: 'Nike',
      countInStock: 50,
      rating: 4.5,
      numReviews: 10,
      description: 'High quality nike shirts',
    },
    {
      name: 'Adidas Slim Shirt',
      slug: 'adidas-slim-shirt',
      category: 'Pants',
      image: '/images/27.jpg',
      price: 100,
      brand: 'Adidas',
      countInStock: 100,
      rating: 4.5,
      numReviews: 20,
      description: 'High quality adidas shirts',
    },
    {
      name: 'Puma Slim Shirt',
      slug: 'puma-slim-shirt',
      category: 'Shirts',
      image: '/images/27.jpg',
      price: 90,
      brand: 'Puma',
      countInStock: 200,
      rating: 4.5,
      numReviews: 8,
      description: 'High quality puma shirts',
    },
    {
      name: 'Jordan Slim Shirt',
      slug: 'jordan-slim-shirt',
      category: 'pants',
      image: '/images/27.jpg',
      price: 500,
      brand: 'jordan',
      countInStock: 40,
      rating: 4.5,
      numReviews: 18,
      description: 'High quality jordan shirts',
    },
  ],
};
export default data;
